--Final CREATE tables commands 

CREATE TABLE `LOCATIONS` (
  `Location` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(30) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `Zip_Code` MEDIUMINT UNSIGNED NOT NULL,
  `Office_Phone` BIGINT UNSIGNED NOT NULL,
  `Cost_Of_Living` DECIMAL(5,1) UNSIGNED NOT NULL,
  PRIMARY KEY (`Location`)
);

CREATE TABLE `POSITION_TITLES` (
  `Title` VARCHAR(30) NOT NULL,
  `Division` VARCHAR(20) NOT NULL,
  `Education_Requirement` VARCHAR(20) NOT NULL,
  `Minimum_Salary` BIGINT UNSIGNED NOT NULL,
  `Maximum_Salary` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Title`)
);

CREATE TABLE `EMPLOYEES` (
  `Employee_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(20) NOT NULL,
  `Last_Name` VARCHAR(20) NOT NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `Title` VARCHAR(30) NOT NULL,
  `Salary` INT UNSIGNED NOT NULL,
  `Location` VARCHAR(20) NOT NULL,
  `Hire_Date` DATE NOT NULL,
  `Probation_Status` VARCHAR(3) NOT NULL,
  `Manager_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Employee_ID`),
  CONSTRAINT `Location` FOREIGN KEY (`Location`) REFERENCES `LOCATIONS` (`Location`),
  CONSTRAINT `Title` FOREIGN KEY (`Title`) REFERENCES `POSITION_TITLES` (`Title`)
);

CREATE TABLE `REVIEW` (
  `Review_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Review_Year` Year NOT NULL,
  `Employee_ID` INT UNSIGNED NOT NULL,
  `Performance` VARCHAR(20) NOT NULL,
  `Raise` DECIMAL(3,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`Review_ID`),
  KEY `Employee_ID_idx` (`Employee_ID`),
  CONSTRAINT `Employee_ID` FOREIGN KEY (`Employee_ID`) REFERENCES `EMPLOYEES` (`Employee_ID`)
);



LOAD DATA LOCAL INFILE "/home/team03/LOCATIONS.csv"
INTO TABLE LOCATIONS
COLUMNS TERMINATED BY ',' 
LINES TERMINATED BY '\n';


LOAD DATA LOCAL INFILE "/home/team03/POSITION_TITLES.csv"
INTO TABLE POSITION_TITLES
COLUMNS TERMINATED BY ',' 
LINES TERMINATED BY '\n';


LOAD DATA LOCAL INFILE "/home/team03/EMPLOYEES.csv"
INTO TABLE EMPLOYEES
COLUMNS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE "/home/team03/REVIEW.csv"
INTO TABLE REVIEW
COLUMNS TERMINATED BY ',' 
LINES TERMINATED BY '\n';
